name: ahilyanagar
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.0.0
  camera: ^0.11.1
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  path_provider: ^2.1.5
  google_mlkit_face_detection: ^0.13.1
  permission_handler: ^11.0.1
  tflite_flutter: ^0.11.0
  image: ^4.5.3
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  intl: ^0.20.2
  fl_chart: ^0.63.0
  printing: ^5.11.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.9

flutter_icons:
  android: true
  ios: true

flutter:
  assets:
    - assets/scan_selfie.svg
    - assets/mobile_face_net.tflite

  uses-material-design: true


flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
